name: Deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install GPG
      run: brew install gnupg
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Decrypt large secret
      run: | 
          if [ "$PROVISIONING_PASSWORD" == "123123" ]
          then 
            echo "Got Secret"
          fi
      env:
        PROVISIONING_PASSWORD: ${{ secrets.PROVISIONING_PASSWORD }}
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.3.app && /usr/bin/xcodebuild -version
    - name: Build archive
      run: xcodebuild -sdk iphoneos -project GithubPipeline/GithubPipeline.xcodeproj -configuration Release -scheme GithubPipeline -derivedDataPath DerivedData -archivePath DerivedData/Archive/GithubPipeline archive
    - name: Export Archive
      run: xcodebuild -exportArchive -archivePath DerivedData/Archive/GithubPipeline.xcarchive -exportOptionsPlist provisioning/App-Store.plist -exportPath DerivedData/ipa
    - name: Dump file hierarchy
      run: ls -R
    - name: Deploy App to Apple
      run: xcrun altool --upload-app --type ios --file DerivedData/ipa/GithubPipeline.ipa --username "${{ secrets.appstore_connect_username }}" --password "${{ secrets.appstore_connect_password }}" --verbose
